import turtle
t = turtle
t.speed(10)

def long(t):
    t.color("grey")
    t.begin_fill()
    t.left(90)
    t.forward(120)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(120)
    t.left(90)
    t.forward(30)
    t.end_fill()

def wide(t):
    t.color("darkgrey")
    t.begin_fill()
    t.forward(90)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(90)
    t.left(90)
    t.forward(200)
    t.end_fill()
    
def window(t):
    t.color("lightblue")
    t.begin_fill()
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.end_fill()

def door(t):
    t.color("brown")
    t.begin_fill()
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(20)
    t.end_fill()

def roof(t):
    t.color("darkred")
    t.begin_fill()
    t.right(30)
    t.forward(60)
    t.right(120)
    t.forward(60)
    t.right(120)
    t.forward(60)
    t.end_fill()

long(t)
wide(t)
t.left(90)
t.forward(120)
long(t)
t.left(90)
t.forward(90)
t.left(90)
t.forward(60)
window(t)
t.color("grey")
t.right(180)
t.forward(40)
t.right(90)
t.forward(25)
door(t)
